spring:
    application:
        name: soteria

    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/soteria?useSSL=false
        username: soteria
        password: soteria

    data:
      mongodb:
        host: localhost
        port: 27017
        database: test

    jpa:
        properties:
            jadira:
              usertype:
                  autoRegisterUserTypes: true
        hibernate:
          naming:
            strategy: org.hibernate.cfg.DefaultNamingStrategy
          ddlAuto: update
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ssZ

    social:
      facebook:
        user-info-url: https://graph.facebook.com/me

security:
  require-ssl: true
  token:
    header: X-Auth-Token
    secret: SECRET-KEY
    expiration: 3600000

keystore:
  path: C:\Users\Korisnik\Desktop\keystore.jks
  password: soteria

secretStore:
  path: C:\Users\Korisnik\Desktop\secretStore.jceks

logging:
  level:
    org.springframework.security: DEBUG

server:
    port: 8443
    ssl:
      key-store: C:\Users\Korisnik\Desktop\keystore.jks
      key-password: soteria
    tomcat:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
