version: '2'

services:
  soteria-mysql:
    image: mysql:5.7.18
    environment:
       MYSQL_USER: soteria
       MYSQL_PASSWORD: soteria
       MYSQL_ROOT_PASSWORD: soteria
       MYSQL_DATABASE: soteria
    ports:
       - "3306:3306"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci